server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/pessoa-docker
#     host: localhost
#     port: 27017
#     database: pessoa-docker

#logging:
#  file: logs/java-mongo-docker-log